<?php

include "Model/Model.php";
include "Class/Reader.php";

class M_Reader extends Model
{
   public function __construct()
   {
      $this->model = new Model();
   }

   public function getAll()
   {
      $result = $this->model->selectAll('reader');
      $arr =[];
      foreach ($result as $item){
         $reader = new Reader($item);
         array_push($arr,$reader);
      }
      return $arr;
   }
   public function delete($table, $column, $value)
   {
      parent::delete($table, $column, $value); // TODO: Change the autogenerated stub

   }
}